[tool.ruff]
target-version = "py39"

[tool.ruff.lint]
extend-select = ["ALL"]
extend-ignore = [
    "FIX002",  # line contains TODO
    "TD003",  # TODO without link to issue
]

[tool.mypy]
strict = true
