#define CONFIG_KEYLOG_ENABLE 1
#define CONFIG_KEYLOG_SIZE 40
#define CONFIG_QP_LOG_ENABLE 1
#define CONFIG_QP_LOG_N_CHARS 70
#define CONFIG_QP_LOG_N_LINES 9
#define CONFIG_QP_ASSETS_SIZE 30
#define CONFIG_QP_COMPUTER_STATS_SIZE 30
#define CONFIG_ALLOC_ALLOCATORS_SIZE 10
#define CONFIG_ALLOC_ALLOCATIONS_SIZE 100
#define CONFIG_CRASH_UNWIND_DEPTH 100
#define CONFIG_CRASH_MESAGE_LENGTH 200
#define CONFIG_GLITCH_TEXT_N_WORKERS 15
#define CONFIG_LOGGING_FORMAT "[%T] (%LS): %M"
#define CONFIG_KASAN_INIT_DELAY 3000
#define CONFIG_KASAN_REDZONE_SIZE 4
#define CONFIG_KASAN_MALLOC_ARRAY_SIZE 300
#define CONFIG_SCROLLING_TEXT_N_WORKERS 15
