exclude: |
  (?x)^(
    arm_math_m0/src/(.*)
    |micropython/src/(.*)
  )$

ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        args:
          [
            "--license-filepath=license.inc",
            "--comment-style=//",
          ]
        exclude: users/elpekenin/include/elpekenin/autoconf.h
        types_or: [c, c++]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
  - repo: local
    hooks:
      - id: stubs
        name: generate stubs
        entry: euc stubs
        language: python
        types: [c]
        files: micropython/user_c_modules/(.*)/(.*).c
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
        args: [--strict]
        additional_dependencies: [
          gitpython,
          hawkmoth,
          kconfiglib,
          qmk,
          sphinx,
          types-tqdm,
          typing_extensions,
        ]
  - repo: local
    hooks:
      - id: schema
        name: generate jsonschema
        entry: euc jsonschema
        language: python
        types: [python]
        files: |
            (?x)^(
                elpekenin_userspace/build.py
                |elpekenin_userspace/commands/jsonschema.py
                |elpekenin_userspace/operations/(.*)
            )$
        pass_filenames: false
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-w]
        exclude: (.*)autocorrect(.*)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
