[tool.ruff]
target-version = "py39"
exclude = ["modules"]

[tool.ruff.lint]
extend-select = ["ALL"]
extend-ignore = [
    "FIX002",  # line contains TODO
    "TD003",  # TODO without link to issue
]

[tool.mypy]
python_version = "3.9"
strict = true
exclude = ["modules"]
