# THIS FILE WAS GENERATED

# Copyright Pablo Martinez (@elpekenin) <elpekenin@elpekenin.dev>
# SPDX-License-Identifier: GPL-2.0-or-later

#
# QMK
#
DYNAMIC_KEYMAP_LAYER_COUNT=5
MAX_DEFERRED_EXECUTORS=64
LAYER_STATE_8BIT=yes
# LAYER_STATE_16BIT is not set
# LAYER_STATE_32BIT is not set
HOLD_ON_OTHER_KEY_PRESS=yes
TAPPING_TERM=200

#
# features
#
ANALOG_DRIVER_REQUIRED=yes
AUTOCORRECT_ENABLE=yes
BOOTMAGIC_ENABLE=yes
DEBUG_ENABLE=yes
CONSOLE_ENABLE=yes
DEFERRED_EXEC_ENABLE=yes
EXTRAKEY_ENABLE=yes
KEY_OVERRIDE_ENABLE=yes
KEYCODE_STRING_ENABLE=yes
QUANTUM_PAINTER_ENABLE=yes
RGB_MATRIX_ENABLE=yes
TAP_DANCE_ENABLE=yes
TRI_LAYER_ENABLE=yes
UART_DRIVER_REQUIRED=yes
WPM_ENABLE=yes
XAP_ENABLE=yes
# end of features

#
# quantum painter
#
# QUANTUM_PAINTER_DEBUG is not set
QUANTUM_PAINTER_DISPLAY_TIMEOUT=0
QUANTUM_PAINTER_NUM_FONTS=4
QUANTUM_PAINTER_NUM_IMAGES=16
QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS=yes
# end of quantum painter

#
# rgb
#
RGB_MATRIX_DEFAULT_VAL=30
RGB_MATRIX_MAXIMUM_BRIGHTNESS=150

#
# effects
#
# ENABLE_RGB_MATRIX_ALPHAS_MODS is not set
# ENABLE_RGB_MATRIX_GRADIENT_UP_DOWN is not set
# ENABLE_RGB_MATRIX_GRADIENT_LEFT_RIGHT is not set
# ENABLE_RGB_MATRIX_BREATHING is not set
# ENABLE_RGB_MATRIX_BAND_SAT is not set
# ENABLE_RGB_MATRIX_BAND_VAL is not set
# ENABLE_RGB_MATRIX_BAND_PINWHEEL_SAT is not set
# ENABLE_RGB_MATRIX_BAND_PINWHEEL_VAL is not set
# ENABLE_RGB_MATRIX_BAND_SPIRAL_SAT is not set
# ENABLE_RGB_MATRIX_BAND_SPIRAL_VAL is not set
# ENABLE_RGB_MATRIX_CYCLE_ALL is not set
ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT=yes
# ENABLE_RGB_MATRIX_CYCLE_UP_DOWN is not set
# ENABLE_RGB_MATRIX_CYCLE_OUT_IN is not set
# ENABLE_RGB_MATRIX_CYCLE_OUT_IN_DUAL is not set
# ENABLE_RGB_MATRIX_RAINBOW_MOVING_CHEVRON is not set
# ENABLE_RGB_MATRIX_CYCLE_PINWHEEL is not set
# ENABLE_RGB_MATRIX_CYCLE_SPIRAL is not set
# ENABLE_RGB_MATRIX_DUAL_BEACON is not set
# ENABLE_RGB_MATRIX_RAINBOW_BEACON is not set
# ENABLE_RGB_MATRIX_RAINBOW_PINWHEELS is not set
# ENABLE_RGB_MATRIX_FLOWER_BLOOMING is not set
# ENABLE_RGB_MATRIX_RAINDROPS is not set
# ENABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS is not set
# ENABLE_RGB_MATRIX_HUE_BREATHING is not set
# ENABLE_RGB_MATRIX_HUE_PENDULUM is not set
# ENABLE_RGB_MATRIX_HUE_WAVE is not set
# ENABLE_RGB_MATRIX_PIXEL_FRACTAL is not set
# ENABLE_RGB_MATRIX_PIXEL_FLOW is not set
# ENABLE_RGB_MATRIX_PIXEL_RAIN is not set
# ENABLE_RGB_MATRIX_TYPING_HEATMAP is not set
# ENABLE_RGB_MATRIX_DIGITAL_RAIN is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_SIMPLE is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_CROSS is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTICROSS is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_NEXUS is not set
# ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTINEXUS is not set
ENABLE_RGB_MATRIX_SPLASH=yes
# ENABLE_RGB_MATRIX_MULTISPLASH is not set
# ENABLE_RGB_MATRIX_SOLID_SPLASH is not set
# ENABLE_RGB_MATRIX_SOLID_MULTISPLASH is not set
# ENABLE_RGB_MATRIX_STARLIGHT is not set
# ENABLE_RGB_MATRIX_STARLIGHT_SMOOTH is not set
# ENABLE_RGB_MATRIX_STARLIGHT_DUAL_HUE is not set
# ENABLE_RGB_MATRIX_STARLIGHT_DUAL_SAT is not set
# ENABLE_RGB_MATRIX_RIVERFLOW is not set
# end of effects
# end of rgb

#
# split
#
RPC_M2S_BUFFER_SIZE=80
RPC_S2M_BUFFER_SIZE=80
SPLIT_ACTIVITY_ENABLE=yes
# SPLIT_HAPTIC_ENABLE is not set
SPLIT_LAYER_STATE_ENABLE=yes
SPLIT_LED_STATE_ENABLE=yes
SPLIT_MODS_ENABLE=yes
# SPLIT_OLED_ENABLE is not set
# SPLIT_POINTING_ENABLE is not set
SPLIT_TRANSPORT_MIRROR=yes
SPLIT_WPM_ENABLE=yes
# end of split
# end of QMK

#
# userspace
#
# KEYLOG_ENABLE is not set
SIPO_PINS_ENABLE=yes
N_SIPO_PINS=8

#
# logging
#
QP_LOG_ENABLE=yes
QP_LOG_N_CHARS=70
QP_LOG_N_LINES=9
SPLIT_LOG_ENABLE=yes
SPLIT_LOG_BUFFER_SIZE=200
SPLIT_LOG_SYNC_DELAY=1000
SPLIT_LOG_SYNC_INTERVAL=3000
UART_LOG_ENABLE=yes
UART_LOG_BAUD_RATE=9600
UART_CLIENT=1
# UART_CLIENT_NONE is not set
UART_CLIENT_PUTTY=yes
XAP_LOG_ENABLE=yes
XAP_LOG_BUFFER_SIZE=200
# end of logging

#
# quantum painter
#
QP_ASSETS_SIZE=30
QP_TASK_COMPUTER_STATS_ENABLE=yes
QP_TASK_COMPUTER_STATS_REDRAW_INTERVAL=500
QP_TASK_COMPUTER_STATS_SIZE=30
QP_TASK_COMPUTER_STATS_TIMEOUT=5000
QP_TASK_GITHUB_NOTIFICATIONS_ENABLE=yes
QP_TASK_GITHUB_NOTIFICATIONS_REDRAW_INTERVAL=500
QP_TASK_GITHUB_NOTIFICATIONS_TIMEOUT=5000
QP_TASK_HEAP_STATS_ENABLE=yes
QP_TASK_HEAP_STATS_REDRAW_INTERVAL=500
QP_TASK_KEYLOG_ENABLE=yes
QP_TASK_KEYLOG_REDRAW_INTERVAL=100
QP_TASK_LAYER_ENABLE=yes
QP_TASK_LAYER_REDRAW_INTERVAL=100
QP_TASK_LOGGING_ENABLE=yes
QP_TASK_LOGGING_REDRAW_INTERVAL=100
QP_TASK_UPTIME_ENABLE=yes
# end of quantum painter

#
# touch screen
#
TOUCH_SCREEN_ENABLE=yes
# end of touch screen
# end of userspace

#
# modules
#

#
# allocator
#
ALLOC_ALLOCATORS_SIZE=10
ALLOC_ALLOCATIONS_SIZE=100
# end of allocator

#
# crash
#
CRASH_UNWIND_DEPTH=100
CRASH_MESAGE_LENGTH=200
# end of crash

#
# glitch text
#
GLITCH_TEXT_N_WORKERS=15
GLITCH_TEXT_TASK_INTERVAL=10
# end of glitch text

#
# logging
#
LOGGING_FORMAT="[%T] (%LS): %M"
# end of logging

#
# sanitizer
#
KASAN_INIT_DELAY=3000
KASAN_REDZONE_SIZE=4
KASAN_MALLOC_ARRAY_SIZE=300
# end of sanitizer

#
# scrolling text
#
SCROLLING_TEXT_N_WORKERS=15
SCROLLING_TEXT_TASK_INTERVAL=10
# end of scrolling text
# end of modules
