// THIS FILE WAS GENERATED

// Copyright Pablo Martinez (@elpekenin) <elpekenin@elpekenin.dev>
// SPDX-License-Identifier: GPL-2.0-or-later

// clang-format off

#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5
#define EECONFIG_USER_DATA_SIZE 16
#define HOLD_ON_OTHER_KEY_PRESS 1
#define LAYER_STATE_8BIT 1
#define TAPPING_TERM 200
#define ANALOG_DRIVER_REQUIRED 1
#define AUTOCORRECT_ENABLE 1
#define CONSOLE_ENABLE 1
#define DEFERRED_EXEC_ENABLE 1
#define MAX_DEFERRED_EXECUTORS 64
#define EXTRAKEY_ENABLE 1
#define KEY_OVERRIDE_ENABLE 1
#define KEYCODE_STRING_ENABLE 1
#define QUANTUM_PAINTER_ENABLE 1
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
#define QUANTUM_PAINTER_NUM_FONTS 20
#define QUANTUM_PAINTER_NUM_IMAGES 16
#define RGB_MATRIX_ENABLE 1
#define RGB_MATRIX_MODE_NAME_ENABLE 1
#define RGB_MATRIX_DEFAULT_VAL 30
#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 150
#define ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT 1
#define ENABLE_RGB_MATRIX_SPLASH 1
#define SPLIT_KEYBOARD 1
#define RPC_M2S_BUFFER_SIZE 80
#define RPC_S2M_BUFFER_SIZE 80
#define SPLIT_ACTIVITY_ENABLE 1
#define SPLIT_WATCHDOG_ENABLE 1
#define SPLIT_WATCHDOG_TIMEOUT 3000
#define SPLIT_LAYER_STATE_ENABLE 1
#define SPLIT_LED_STATE_ENABLE 1
#define SPLIT_MODS_ENABLE 1
#define SPLIT_TRANSPORT_MIRROR 1
#define SPLIT_WPM_ENABLE 1
#define TAP_DANCE_ENABLE 1
#define TRI_LAYER_ENABLE 1
#define UART_DRIVER_REQUIRED 1
#define WPM_ENABLE 1
#define XAP_ENABLE 1
#define SIPO_PINS_ENABLE 1
#define N_SIPO_PINS 8
#define QP_LOG_ENABLE 1
#define QP_LOG_N_CHARS 70
#define QP_LOG_N_LINES 13
#define QP_LOGGING_UI_REDRAW_INTERVAL 100
#define QP_ASSETS_SIZE 30
#define COMPUTER_STATS_SIZE 30
#define COMPUTER_STATS_UI_REDRAW_INTERVAL 500
#define COMPUTER_STATS_UI_TIMEOUT 5000
#define BUILD_MATCH_UI_REDRAW_INTERVAL 500
#define GITHUB_NOTIFICATIONS_UI_REDRAW_INTERVAL 500
#define GITHUB_NOTIFICATIONS_UI_TIMEOUT 5000
#define TOUCH_SCREEN_ENABLE 1

#define FOREACH_AUTOCONF(X) \
    X(DYNAMIC_KEYMAP_LAYER_COUNT) \
    X(EECONFIG_USER_DATA_SIZE) \
    X(HOLD_ON_OTHER_KEY_PRESS) \
    X(LAYER_STATE_8BIT) \
    X(TAPPING_TERM) \
    X(ANALOG_DRIVER_REQUIRED) \
    X(AUTOCORRECT_ENABLE) \
    X(CONSOLE_ENABLE) \
    X(DEFERRED_EXEC_ENABLE) \
    X(MAX_DEFERRED_EXECUTORS) \
    X(EXTRAKEY_ENABLE) \
    X(KEY_OVERRIDE_ENABLE) \
    X(KEYCODE_STRING_ENABLE) \
    X(QUANTUM_PAINTER_ENABLE) \
    X(QUANTUM_PAINTER_DISPLAY_TIMEOUT) \
    X(QUANTUM_PAINTER_NUM_FONTS) \
    X(QUANTUM_PAINTER_NUM_IMAGES) \
    X(RGB_MATRIX_ENABLE) \
    X(RGB_MATRIX_MODE_NAME_ENABLE) \
    X(RGB_MATRIX_DEFAULT_VAL) \
    X(RGB_MATRIX_MAXIMUM_BRIGHTNESS) \
    X(ENABLE_RGB_MATRIX_CYCLE_LEFT_RIGHT) \
    X(ENABLE_RGB_MATRIX_SPLASH) \
    X(SPLIT_KEYBOARD) \
    X(RPC_M2S_BUFFER_SIZE) \
    X(RPC_S2M_BUFFER_SIZE) \
    X(SPLIT_ACTIVITY_ENABLE) \
    X(SPLIT_WATCHDOG_ENABLE) \
    X(SPLIT_WATCHDOG_TIMEOUT) \
    X(SPLIT_LAYER_STATE_ENABLE) \
    X(SPLIT_LED_STATE_ENABLE) \
    X(SPLIT_MODS_ENABLE) \
    X(SPLIT_TRANSPORT_MIRROR) \
    X(SPLIT_WPM_ENABLE) \
    X(TAP_DANCE_ENABLE) \
    X(TRI_LAYER_ENABLE) \
    X(UART_DRIVER_REQUIRED) \
    X(WPM_ENABLE) \
    X(XAP_ENABLE) \
    X(SIPO_PINS_ENABLE) \
    X(N_SIPO_PINS) \
    X(QP_LOG_ENABLE) \
    X(QP_LOG_N_CHARS) \
    X(QP_LOG_N_LINES) \
    X(QP_LOGGING_UI_REDRAW_INTERVAL) \
    X(QP_ASSETS_SIZE) \
    X(COMPUTER_STATS_SIZE) \
    X(COMPUTER_STATS_UI_REDRAW_INTERVAL) \
    X(COMPUTER_STATS_UI_TIMEOUT) \
    X(BUILD_MATCH_UI_REDRAW_INTERVAL) \
    X(GITHUB_NOTIFICATIONS_UI_REDRAW_INTERVAL) \
    X(GITHUB_NOTIFICATIONS_UI_TIMEOUT) \
    X(TOUCH_SCREEN_ENABLE)
