#!/bin/bash

# Utility script to compile both halves at once (with EE_HANDS)

KB=elpekenin/access
KM=elpekenin
LOG_FOLDER=users/elpekenin/logs
mkdir -p $LOG_FOLDER

for SIDE in left right
do
    qmk compile \
        -kb $KB \
        -km $KM \
        --compiledb \
        -e MAKECMDGOALS=uf2-split-$SIDE \
        -e TARGET=$SIDE \
        > $LOG_FOLDER/compile.txt 2>&1 \
        || exit 1
done
