#!/bin/bash

# Utility script to compile both halves at once (with EE_HANDS)

KB=elpekenin/access
KM=elpekenin

LOG_FOLDER=$(realpath ./users/elpekenin/logs)
mkdir -p $LOG_FOLDER

OUT=$LOG_FOLDER/compile.out
ERR=$LOG_FOLDER/compile.err

for SIDE in left right
do
    qmk compile \
        -kb $KB \
        -km $KM \
        --compiledb \
        -e MAKECMDGOALS=uf2-split-$SIDE \
        -e LOG_FOLDER=$LOG_FOLDER \
        -e TARGET=$SIDE \
        > $OUT 2> $ERR \
        || (cat $OUT && echo '' && cat $ERR && exit 1)
done
