#!/bin/bash

# Utility script to compile both halves at once (with EE_HANDS)

KB=elpekenin/access
KM=elpekenin

for SIDE in left right
do
    qmk compile \
        -kb $KB \
        -km $KM \
        -e MAKECMDGOALS=uf2-split-$SIDE \
        -e TARGET=$SIDE
done
